### ISSUE TITLE
FATAL Error Code #456

### ISSUE THREAD

**Issue by gtejani** [Clika/clika_compression_examples#1]
Hi, 
I was trying to run clika compression on STD PAN++ model, and I ran into an error as follows, 

```
[2023-09-05 14:39:54] Version: 0.1.2
Created log at: outputs/logs/clika_optimize_2023-09-05_14:39:54.928899.log
[2023-09-05 14:39:54] Initializing output directory at: 'outputs/logs'
[2023-09-05 14:39:54] Starting Single-GPU optimization
reading type: cv2.
[2023-09-05 14:39:56] 
Training Settings:
        +                              num_epochs = 5
        +                         steps_per_epoch = 772
        +                        evaluation_steps = -1
        +                             stats_steps = 20
        +   reset_training_dataset_between_epochs = False
        + reset_evaluation_dataset_between_epochs = False
        +                          print_interval = 10
        +               print_num_steps_averaging = 1
        +                           save_interval = 1
        +                     use_mixed_precision = False
        +                        use_fp16_weights = False
        +                use_gradients_checkpoint = False
        +                grads_accumulation_steps = 1
        +                        lr_warmup_epochs = 0
        +               lr_warmup_steps_per_epoch = 0
        +                             random_seed = 1693892647
        +                 skip_initial_evaluation = False

Global Quantization Settings:
        + quantization_algorithm = Quantization Aware Training
        +       weights_num_bits = 8
        +   activations_num_bits = 8

Deployment Settings:
        + target_framework = TensorRT
        +     Graph Author = CLIKA

[2023-09-05 14:39:56] Collecting Models Outputs for: 20 steps
reading type: cv2.
[2023-09-05 14:40:10] Collecting Outputs        [20/20] eta: 0:00:00            iter-time: 0.672s       data-time: 0.338s       sys-mem: 115967MiB      vmem: 5597MB
[2023-09-05 14:40:10] Collecting Outputs Total time: 0:00:13
[2023-09-05 14:40:15] FATAL Error Code #456
Traceback (most recent call last):
  File "/home/jovyan/workspace/1_user/user@agilesoda.ai/clika/std/resnet50/std_main.py", line 391, in <module>
    main(config=args)
  File "/home/jovyan/workspace/1_user/user@agilesoda.ai/clika/std/resnet50/std_main.py", line 335, in main
    run_compression(
  File "/home/jovyan/workspace/1_user/user@agilesoda.ai/clika/std/resnet50/std_main.py", line 178, in run_compression
    final = engine.optimize(
  File "/opt/conda/envs/clika2/lib/python3.9/site-packages/clika_compression/runners/pytorch_compression_engine.py", line 44, in optimize
    return engine.optimize(output_path,
  File "", line 0, in 
  File "", line 0, in 
ValueError: Unknown Error.
```

Since the logs do not provide any error trace, I can't figure out the source. Do you have any idea about that?

Thank you!

**Comment by jl749** [comment]
Hi @gtejani 
Thank you for participating in our beta service.

**FATAL Error #456** is caused by unsupported tensor ops arguments. 
In your case, likely **rounding_mode** or **out** arguments inside `torch.div()` or `a // b`.

We will improve the error messages and expand supported operations/layers in future releases. 
However, without the specific source code we cannot diagnose the problem more specifically.

To further assist you with your inquiry, please email us at [jlee@clika.io](). 
We are currently using email channels for product support related to the beta service and we will be happy to help you there.


Thank you

**Comment by gtejani** [comment]
Hi @jl749,
Thank you for your quick reply. 

I am using torch.div() function (I used it to replace // as it was giving floordiv function error earlier).
Anyway, for now, I have skipped using torch.div() as well and it is working. 

I will contact you through email if any further help is needed.

Thank you!
